# Required sample sheet columns:
# sample, reference_fasta, r1, r2
# Optional sample sheet column:
# bed
sample_sheet: example_sample_sheet.csv
res_dir: /path/to/results_directory

# fastp parameters
fastp_min_base_quality: 20
fastp_min_read_length: 30
fastp_extra: ""


# BWA MEM parameters
bwa_T: 30 # minimum score to output an alignment
bwa_h: 5 # if there are <INT hits with score >80.00% of the max score, output all in XA [5,200]
bwa_mem_extra: ""

# samtools filtering after mapping
samtools_filtering_post_mapping_f : "3" # require both reads to be properly paired
samtools_filtering_post_mapping_F : "4" # exclude unmapped reads
samtools_filtering_post_mapping_q: 15 # MAPQ score

# ivar trimming parameters
ivar_min_length_after_trimming: 50
ivar_trim_offset: 0
ivar_trim_q: 20 # Minimum quality threshold for sliding window to pass
ivar_trim_s: 4 # Sliding window size for trimming, in bases 


# ivar consensus parameters
cons_mpileup_A: True # include anomalous read pairs in mpileup
cons_mpileup_a: True # output all positions in mpileup, even those with zero coverage
cons_mpileup_d: 0 # max per-file depth for mpileup 
cons_mpileup_Q: 0 # minimum base quality for mpileup
cons_ivar_min_variant_quality: 30 # Phred score
cons_ivar_min_consensus_frequency: 0.75
cons_ivar_min_depth: 20

# ivar variant calling parameters
ivar_variant_mpileup_A: True # include anomalous read pairs in mpileup
ivar_variant_mpileup_d: 0 # max per-file depth for mpileup 
ivar_variant_mpileup_B: True #  disable BAQ (per-Base Alignment Quality)
ivar_variant_mpileup_Q: 0 # minimum base quality for mpileup
ivar_variant_min_variant_quality: 30 # Phred score
ivar_variant_t: 0.0 # minimum allele frequency threshold for variant callin

# lofreq filter parameters
lofreq_filter_no_defaults : True
lofreq_filter_v: 20
lofreq_filter_V: 0
lofreq_filter_a: 0.1
lofreq_filter_A : 0.0

# bcftools normalize parameters
bcftools_normalize_check_ref: "w"
bcftools_normalize_site_win: 1000
bcftools_normalize_sort: "pos"
bcftools_normalize_out_type: "v"

# bamdash parameters
bamdash_bs: 10
