# Required sample sheet columns:
# sample, reference_fasta, r1, r2
# Optional sample sheet column:
# bed
sample_sheet: sample_sheet.tsv

# fastp parameters
min_base_quality: 20
min_read_length: 30
fastp_extra: ""


# samtools view filtering
min_mapping_quality: 20 # MAPQ score

# variant calling parameters
min_allele_frequency_variant: 0.1


# ivar trimming parameters
min_length_after_trimming: 50


# ivar consensus parameters
min_variant_quality: 30 # Phred score
min_consensus_frequency: 0.75
min_depth: 20

# BWA MEM parameters
bwa_mem_extra: ""

run_denovo: true
run_metagenomics: false
build_snpeff_db: false
